spring.application.name=Facturacion Clientes

# ----------------------------------------------------
# 1. Configuración de la URL de la Base de Datos (SQL Server)
# ----------------------------------------------------
spring.datasource.url=${DB_URL}

# ----------------------------------------------------
# 2. Credenciales
# ----------------------------------------------------
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ----------------------------------------------------
# 3. Driver 
# ----------------------------------------------------
# Para SQL Server (Microsoft Data SQL Client):
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ----------------------------------------------------
# 4. Configuración adicional
# ----------------------------------------------------
# Pool de conexiones (Hikari por defecto en Spring Boot)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
# logging.level.com.zaxxer.hikari=INFO

# Dialecto de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false 

# --- DEBUGGING
logging.level.root=INFO
logging.level.org.app=DEBUG

# Configuracion Bsale API
bsale.api.url=${BSALE_URL}
bsale.api.token=${BSALE_TOKEN}

# Configuracion de n8n
n8n.base.url=${N8N_BASE_URL}
n8n.hooks.create-excel=${N8N_EXCEL_HOOK}

# Bsale Invoice config
bsale.config.invoice.office-id=${BSALE_INVOICE_OFFICE_ID}
bsale.config.invoice.document-type-id=${BSALE_INVOICE_DOCUMENT_TYPE}
bsale.config.invoice.coin-id=${BSALE_INVOICE_COIN_ID}
bsale.config.invoice.tax-id=${BSALE_INVOICE_TAX_IGV_ID}
bsale.config.invoice.dynamic-attribute-oc-id=${BSALE_DOC_ATTR_ID}

# Pago - Cuotas
bsale.config.invoice.payment-types.due=${BSALE_PAYMENT_DUE_ID}
bsale.config.invoice.payment-types.detraction=${BSALE_PAYMENT_DETRACTION_ID}

# Detracción - Medio de pago
bsale.config.invoice.detraction.payment-method.form-id=${BSALE_DETRACTION_PAY_TYPE_ID}
bsale.config.invoice.detraction.payment-method.value-id=${BSALE_DETRACTION_PAY_TYPE_VALUE}

# Detracción - Cuenta de banco
bsale.config.invoice.detraction.bank-account.form-id=${BSALE_DETRACTION_BANK_FORM_ID}
bsale.config.invoice.detraction.bank-account.value-id=${BSALE_DETRACTION_BANK_FORM_VALUE}

# Detracción - Bien/Servicio
bsale.config.invoice.detraction.service-code.form-id=${BSALE_DETRACTION_SERVICE_ID}
bsale.config.invoice.detraction.service-code.value-id=${BSALE_DETRACTION_SERVICE_VALUE}

# Tipo Operación (Form 83, Value 1)
bsale.config.invoice.detraction.operation-type.form-id=${BSALE_DETRACTION_OP_ID}
bsale.config.invoice.detraction.operation-type.value-id=${BSALE_DETRACTION_OP_VALUE}

# Configuracion de mail
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# API KEY
app.api.key=${APP_API_KEY}

# Server configuration
server.port=${SERVER_PORT}